#!/bin/bash
# Generate comprehensive diagnostic report

REPORT_DIR="/home/openclaw/.openclaw/workspace/diagnostics/reports"
mkdir -p "$REPORT_DIR"

REPORT_FILE="$REPORT_DIR/diagnostic-report-$(date +%Y%m%d_%H%M%S).md"

cat > "$REPORT_FILE" << 'HEADER'
# OpenClaw Diagnostic Report

**Generated:** $(date)
**System:** vm-axvC6iBU
**OpenClaw Version:** $(openclaw --version 2>/dev/null || echo "N/A")

---

## 1. System Overview

HEADER

# System info
{
    echo "### Host Information"
    echo '```'
    uname -a
    echo '```'
    echo ""
    echo "### Uptime"
    echo '```'
    uptime
    echo '```'
    echo ""
} >> "$REPORT_FILE"

# Memory
{
    echo "## 2. Memory Usage"
    echo '```'
    free -h
    echo '```'
    echo ""
} >> "$REPORT_FILE"

# Disk
{
    echo "## 3. Disk Usage"
    echo '```'
    df -h
    echo '```'
    echo ""
} >> "$REPORT_FILE"

# Gateway
{
    echo "## 4. Gateway Status"
    echo '```'
    systemctl status openclaw-gateway --no-pager | head -15
    echo '```'
    echo ""
    echo "### Gateway Process"
    echo '```'
    ps aux | grep openclaw-gateway | grep -v grep || echo "Not found"
    echo '```'
    echo ""
} >> "$REPORT_FILE"

# Network
{
    echo "## 5. Network Status"
    echo ""
    echo "### LLM API Health"
    echo '```'
    curl -s http://10.1.160.84:9527/health 2>/dev/null || echo "Failed"
    echo '```'
    echo ""
    echo "### Available Models"
    echo '```'
    if [ -n "$API_HUB_KEY" ]; then
        curl -s -H "Authorization: Bearer $API_HUB_KEY" http://10.1.160.84:9527/v1/models 2>/dev/null | head -20 || echo "Failed"
    else
        echo "API_HUB_KEY not set"
    fi
    echo '```'
    echo ""
} >> "$REPORT_FILE"

# Errors
{
    echo "## 6. Recent Errors (Last 30 minutes)"
    echo '```'
    journalctl -u openclaw-gateway --since "30 minutes ago" 2>/dev/null | grep -i error | tail -20 || echo "None"
    echo '```'
    echo ""
} >> "$REPORT_FILE"

# Sessions
{
    echo "## 7. Session Information"
    echo ""
    echo "### Session Count"
    echo '```'
    find ~/.openclaw/sessions -name "*.jsonl" 2>/dev/null | wc -l
    echo '```'
    echo ""
} >> "$REPORT_FILE"

# Processes
{
    echo "## 8. Background Processes"
    echo ""
    echo "### Trading Monitors"
    echo '```'
    ps aux | grep -E '(auto-monitor|continuous-trading-monitor)' | grep -v grep || echo "None"
    echo '```'
    echo ""
} >> "$REPORT_FILE"

# Files
{
    echo "## 9. File Information"
    echo ""
    echo "### OpenClaw Directory Size"
    echo '```'
    du -sh ~/.openclaw
    echo '```'
    echo ""
    echo "### Log Files"
    echo '```'
    ls -lh /tmp/openclaw-1000/*.log 2>/dev/null | tail -5 || echo "No log files"
    echo '```'
    echo ""
} >> "$REPORT_FILE"

# Summary
{
    echo "## 10. Summary"
    echo ""
    echo "This report was automatically generated by the diagnostic suite."
    echo ""
    echo "### Quick Actions"
    echo ""
    echo "- Run health check: \`cd diagnostics && ./health-check.sh\`"
    echo "- Monitor logs: \`cd diagnostics && ./log-monitor.sh\`"
    echo "- View detailed analysis: \`cat diagnostics/FINAL_REPORT.md\`"
    echo "- Run automated fixes: \`cd diagnostics && ./quick-fix-v2.sh\`"
    echo ""
    echo "### For detailed analysis and recommendations, see:"
    echo ""
    echo "- \`SYSTEM_VERDICT.md\` - Initial system analysis"
    echo "- \`FINAL_REPORT.md\` - Current system status"
    echo "- \`README.md\` - Complete usage guide"
    echo ""
    echo "---"
    echo ""
    echo "**Report Generation:** Complete"
    echo "**Diagnostic Suite:** OpenClaw v2026.4.25"
    echo ""
} >> "$REPORT_FILE"

echo "=========================================="
echo "Diagnostic Report Generated"
echo "=========================================="
echo ""
echo "Report saved to: $REPORT_FILE"
echo ""
echo "View report:"
echo "  cat $REPORT_FILE"
echo ""
echo "Or:"
echo "  less $REPORT_FILE"
echo ""